#!/bin/bash
aws ec2 stop-instances --instance-ids $(aws ec2 describe-instances --filter "Name=tag:Name,Values="$1""|\
  jq '.Reservations[].Instances[] | {InstanceId}'|\
  tr '"' '\n'|tail -n 3|head -n 1|tr -d '\n')
